class Autogenerated {
  List<QuestionsData>? questionsData;

  Autogenerated({this.questionsData});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['QuestionsData'] != null) {
      questionsData = <QuestionsData>[];
      json['QuestionsData'].forEach((v) {
        questionsData!.add(new QuestionsData.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.questionsData != null) {
      data['QuestionsData'] =
          this.questionsData!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class QuestionsData {
  int? id;
  String? question;
  bool selected = false;

  QuestionsData({this.id, this.question});

  QuestionsData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    question = json['question'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['question'] = this.question;
    return data;
  }
}