class Autogenerated {
  List<QuestionsData>? questions;

  Autogenerated({this.questions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['questions'] != null) {
      questions = <QuestionsData>[];
      json['questions'].forEach((v) {
        questions!.add(new QuestionsData.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.questions != null) {
      data['questions'] = this.questions!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class QuestionsData {
  int id = 0;
  String? question;
  String? textQuestion;
  List<String>? questionsList;
  bool? end;

  QuestionsData({required this.id, this.question, this.textQuestion, this.questionsList, this.end});

  QuestionsData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    question = json['question'];
    textQuestion = json['textQuestion'];
    questionsList = json['questionsList'].cast<String>();
    end = json['end'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['question'] = this.question;
    data['textQuestion'] = this.textQuestion;
    data['questionsList'] = this.questionsList;
    data['end'] = this.end;
    return data;
  }
}
